language: android
env:
 global:
 - ANDROID_API=29
 - ANDROID_BUILD_TOOLS=29.0.3
before_install:
  cd Android;
android:
  components:
    - tools
    - platform-tools
    - build-tools-$ANDROID_BUILD_TOOLS
    - android-$ANDROID_API
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-google-google_play_services
script:
   - ./gradlew clean assembleDebug check
